from icrawler.builtin import GoogleImageCrawler
import os

# Your game names list
game_list = ['Spider-Man',
 'Red Dead Redemption II',
 'Grand Theft Auto V',
 'God of War',
 "Uncharted 4: A Thief's End",
 'The Last of Us: Part II',
 'Horizon Forbidden West',
 'The Last of Us',
 'Detroit: Become Human',
 'Death Stranding',
 'Ghost of Tsushima',
 'Spider-Man: Miles Morales',
 'Cyberpunk 2077',
 "Uncharted: Drake's Fortune",
 'Batman: Arkham Knight',
 'God of War: Ragnarök',
 'Far Cry 6',
 'Grand Theft Auto: San Andreas',
 'MultiVersus',
 'Far Cry 3',
 'Star Wars Jedi: Fallen Order',
 'Elden Ring',
 'Xenoblade Chronicles 3',
 'Uncharted: The Nathan Drake Collection',
 "Assassin's Creed Valhalla",
 "Marvel's Guardians of the Galaxy",
 'Grand Theft Auto: Vice City',
 'Uncharted 2: Among Thieves',
 'The Witcher 3: Wild Hunt',
 'Fallout: New Vegas',
 'Command & Conquer: Red Alert 3',
 'Horizon Zero Dawn',
 'Red Dead Redemption',
 'Call of Duty: Modern Warfare',
 'Final Fantasy VII Remake',
 'Genshin Impact',
 'The Elder Scrolls V: Skyrim',
 'Fallout 4',
 'Yakuza: Like a Dragon',
 'Days Gone',
 'Squadron 42',
 'Grand Theft Auto IV',
 'Batman: Arkham City',
 "Tiny Tina's Wonderlands",
 'Saints Row',
 "Marvel's Avengers",
 "Assassin's Creed: Odyssey",
 'Far Cry 5',
 'Resident Evil Village',
 'L.A. Noire',
 'Fortnite',
 'The Dark Pictures: House of Ashes',
 'Mortal Kombat 11',
 'Batman: Arkham Asylum',
 'Lego Star Wars: The Skywalker Saga',
 "Assassin's Creed IV: Black Flag",
 'Uncharted: The Lost Legacy',
 'Injustice 2',
 'Predator: Hunting Grounds',
 "Uncharted 3: Drake's Deception",
 'Mass Effect',
 "Assassin's Creed II",
 'Mass Effect 2',
 'Metal Gear Solid V: The Phantom Pain',
 'Apex Legends',
 'Forspoken',
 'Tomb Raider',
 'Ghost Recon: Wildlands',
 'Dying Light 2: Stay Human',
 'Kingdom Hearts III',
 'Saints Row: The Third',
 'Cuphead',
 'Poppy Playtime',
 'Control',
 "Assassin's Creed: Origins",
 'Spider-Man 2',
 'God of War III',
 'Call of Duty: Black Ops',
 'Batman: Arkham Origins',
 'Mass Effect 3',
 'Mass Effect: Legendary Edition',
 'Call of Duty: Modern Warfare 2',
 'Call of Duty: Vanguard',
 'Gotham Knights',
 'Destiny 2',
 'Minecraft',
 'Resident Evil VII: Biohazard',
 "Assassin's Creed III",
 'Mafia: Definitive Edition',
 'Far Cry 4',
 'Suicide Squad: Kill the Justice League',
 'Metal Gear Rising: Revengeance',
 'Call of Duty: WWII',
 'Resident Evil 4',
 'God of War',
 'Saints Row IV',
 'Call of Duty: Modern Warfare II',
 'Resident Evil 2',
 'Resident Evil 4',
 'Grand Theft Auto III',
 'Star Wars Jedi: Survivor',
 'BioShock Infinite',
 'Mass Effect: Andromeda',
 'Fortnite: Chapter 3',
 'The Legend of Zelda: Breath of the Wild',
 'Watch Dogs 2',
 'Saints Row 2',
 'Call of Duty: Black Ops Cold War',
 'BioShock',
 'Borderlands 3',
 'Evil Dead: The Game',
 'Halo Infinite',
 'Dragon Age: Inquisition',
 'Tekken 7',
 'Big Rumble Boxing: Creed Champions',
 'Fallout 3',
 'Grand Theft Auto VI',
 'Mafia III',
 'Beyond: Two Souls',
 'Rise of the Tomb Raider',
 'Max Payne 3',
 'A Way Out',
 'Mafia II',
 'Dying Light',
 'Lego Dimensions',
 'Yakuza 0',
 'Bully',
 'Quantum of Solace',
 'James Bond 007: Everything or Nothing',
 'Devil May Cry 5',
 'Bloodborne',
 'God of War II',
 'Call of Duty: Black Ops II',
 'Sleeping Dogs',
 'Spider-Man 2',
 'Sekiro: Shadows Die Twice',
 'Middle-Earth: Shadow of War',
 'Overwatch',
 'James Bond: World of Espionage',
 'Hitman 3',
 'Resident Evil',
 'Doom',
 'Watch Dogs',
 'Halo 2',
 'Prey',
 'GTAV',
 'The Callisto Protocol',
 'Star Wars: Battlefront II',
 'Scarface: The World Is Yours',
 'Saints Row',
 'Destiny 2: The Witch Queen',
 'Metal Gear Solid',
 'DC League of Super-Pets: The Adventures of Krypto and Ace',
 'Ark II',
 'The Elder Scrolls IV: Oblivion',
 'Ghost Recon: Breakpoint',
 'Resident Evil 3',
 'Shadow of the Tomb Raider',
 'Dishonored',
 "Assassin's Creed",
 'Outlast',
 'Metal Gear Solid 3: Snake Eater',
 'Star Wars: The Old Republic',
 'Spider-Man 3',
 'Ratchet & Clank: Rift Apart',
 'Wolfenstein: The New Order',
 "Assassin's Creed: Brotherhood",
 'Call of Duty 4: Modern Warfare',
 'Persona 5',
 'Half-Life 2',
 'Dota 2',
 'Kingdom Hearts',
 'The Godfather',
 'Resident Evil 6',
 "Assassin's Creed: Unity",
 'Grand Theft Auto: Vice City Stories',
 'Watch Dogs: Legion',
 'Call of Duty: Black Ops III',
 'Deadpool',
 'Payday 2',
 'Kingdom Hearts II',
 'Wolfenstein II: The New Colossus',
 'Super Smash Bros. Ultimate',
 'Dragon Age: Origins',
 'Call of Duty: Infinite Warfare',
 'Coraline',
 'Mad Max',
 'Metro Exodus',
 'Hogwarts Legacy',
 'Xenoblade Chronicles 2',
 'Doom Eternal',
 'Call of Duty: Modern Warfare 3',
 'Lego DC Super-Villains',
 'NieR: Automata',
 'Spider-Man: Web of Shadows',
 'Borderlands 2',
 'Dead Space',
 'Call of Duty: Advanced Warfare',
 'The Elder Scrolls Online',
 'Lollipop Chainsaw',
 'Final Fantasy XV',
 'Max Payne',
 "Five Nights at Freddy's: Security Breach",
 'Resident Evil 5',
 "Hellblade: Senua's Sacrifice",
 'Tekken 3',
 'Command & Conquer: Red Alert 3 - Uprising',
 'Fallout 76',
 'Dishonored 2',
 'Persona 5 Royal',
 'Star Wars: The Force Unleashed',
 "Assassin's Creed: Revelations",
 'Injustice: Gods Among Us',
 'Team Fortress 2',
 'The Evil Within',
 'The Warriors',
 'The Last of Us: Part I',
 'Street Fighter: The Movie',
 'Fable III',
 'The Matrix Awakens: An Unreal Engine 5 Experience',
 'Demon Slayer: The Hinokami Chronicles',
 'M.U.G.E.N',
 'Star Wars: Knights of the Old Republic',
 'Hades',
 'Mob of the Dead',
 'inFamous: Second Son',
 "Assassin's Creed: Syndicate",
 'Top Gun',
 'Halo: Combat Evolved',
 'Mafia: The City of Lost Heaven',
 'Valorant',
 'Hitman',
 'Spider-Man',
 'Grand Theft Auto IV: The Ballad of Gay Tony',
 'World of Warcraft: Battle for Azeroth',
 'Halo 3',
 'Red Dead Revolver',
 'Batman Begins',
 'Dark Souls III',
 'Middle-Earth: Shadow of Mordor',
 'Alien vs. Predator: Evolution',
 'The Sopranos: Road to Respect',
 'Batman: The Telltale Series',
 'The Fifth Element',
 'Total War: Warhammer III',
 'Metal Gear Solid 4: Guns of the Patriots',
 'The Wolf Among Us',
 'Tales of Arise',
 'The Amazing Spider-Man 2',
 'Psychonauts 2',
 'Call of Duty: World at War',
 'The Legend of Zelda: Ocarina of Time',
 'Left 4 Dead 2',
 'League of Legends',
 'Hollow Knight',
 'Gears 5',
 'Xenoblade Chronicles',
 'Dark Souls',
 'Call of Duty: Ghosts',
 'Far Cry Primal',
 "Assassin's Creed: Rogue",
 'Spider-Man: Shattered Dimensions',
 'Hitman 2',
 'Call of Duty: Black Ops 4',
 'Cuphead: The Delicious Last Course',
 'Def Jam: Fight for NY',
 'Outlast 2',
 'Quantum Break',
 'Lego Marvel Super Heroes',
 'Dead or Alive Xtreme 3',
 'Halo 5: Guardians',
 'Halo: Reach',
 'Max Payne 2: The Fall of Max Payne',
 'Half-Life: Alyx',
 'Ghostbusters',
 'Hitman: Absolution',
 'Spider-Man: The City That Never Sleeps',
 'The Outer Worlds',
 'South Park: The Stick of Truth',
 'The Witcher',
 'Shadow the Hedgehog',
 'GoldenEye 007',
 'Final Fantasy XIV: Endwalker',
 'South Park: The Fractured but Whole',
 'Mortal Kombat X',
 'LEGO The Incredibles',
 'Rainbow Six: Siege',
 'Doom',
 'Wolverine',
 'The Evil Within 2',
 'Back to the Future: The Game - 30th Anniversary Edition',
 'Harry Potter and the Deathly Hallows: Part II',
 'God of War: Ghost of Sparta',
 'Call of Duty',
 'Star Wars: The Old Republic - Legacy of the Sith',
 'The Witcher 3: Wild Hunt - Blood and Wine',
 'Sonic Adventure 2',
 'Returnal',
 'Alan Wake',
 'Aliens vs. Predator',
 'Battlefield 1',
 'Command & Conquer: Red Alert 2',
 'Metal Gear Solid 2: Sons of Liberty',
 'Hentai Girl',
 'Cars',
 'Maneater',
 'WWE 2K22',
 'God of War: Ascension',
 'Half-Life',
 'Final Fantasy VII',
 'Destroy All Humans!',
 'Brütal Legend',
 'Titanfall 2',
 'Fast and Furious Crossroads',
 'Far Cry New Dawn',
 'Resident Evil',
 'Prince of Persia: Warrior Within',
 'The Punisher',
 'Halo 4',
 'Midnight Suns',
 'Scarface: Money. Power. Respect.',
 'The Incredible Hulk',
 'Demolition Man',
 'Grand Theft Auto',
 'Toy Story 2',
 'World of Warcraft: Shadowlands',
 'ARK: Survival Evolved',
 'Ultimate Spider-Man',
 'Off the Grid',
 'Manhunt 2',
 "Conker's Bad Fur Day",
 'Fire Emblem Warriors: Three Hopes',
 'Resident Evil 2',
 'Dead Island 2',
 'Sonic the Hedgehog',
 'Skull and Bones',
 'Splinter Cell: Blacklist',
 'The Chronicles of Riddick: Assault on Dark Athena',
 'Lego Marvel Super Heroes 2',
 'Cobra Kai: The Karate Kid Saga Continues',
 'Fallout: A Post-Nuclear Role-Playing Game',
 'Battlefield 2042',
 'Super Mario Bros.',
 'BioShock 2',
 'Super Mario 64',
 'Trollhunters: Defenders of Arcadia',
 'Ryse: Son of Rome',
 'The Chronicles of Riddick: Escape from Butcher Bay',
 'NieR Replicant: ver.1.22474487139...',
 'X-Men Origins: Wolverine',
 'Battlefield V',
 'Game of Thrones',
 'Need for Speed: Most Wanted',
 'Star Wars: Knights of the Old Republic II - The Sith Lords',
 'Prison Break: The Conspiracy',
 'The Witcher 2: Assassins of Kings',
 'Dragon Ball Z: Kakarot',
 'Lost Judgment',
 'Sea of Thieves',
 'Yakuza Kiwami',
 'Borderlands',
 'Far Cry 2',
 'Ghostbusters: Spirits Unleashed',
 'From Russia with Love',
 'A Plague Tale: Requiem',
 'Mortal Kombat',
 'Harry Potter: Hogwarts Mystery',
 'The Lord of the Rings: The Two Towers',
 'Call of Duty: Warzone',
 'GoldenEye 007',
 'Spider-Man: Edge of Time',
 'Star Citizen',
 'Far Cry',
 'Batman: Return to Arkham',
 "Lego Marvel's Avengers",
 'Dragon Age II',
 'Disney Speedstorm',
 'Saints Row: Gat Out of Hell',
 'Diablo III',
 'James Bond 007: Blood Stone',
 'Pillars of Eternity II: Deadfire',
 'Battlefield 4',
 'Lego Batman 3: Beyond Gotham',
 'Marvel Avengers Academy',
 'DmC: Devil May Cry',
 'Left 4 Dead',
 'Forza Horizon 5',
 'Alice: Madness Returns',
 'Deathloop',
 "Crash Bandicoot 4: It's About Time",
 'Sonic the Hedgehog 3',
 'The Last of Us: Left Behind',
 'Pirates of the Caribbean: The Legend of Jack Sparrow',
 'Just Cause 4',
 'Prince of Persia: The Sands of Time',
 'Gun',
 'Batman: The Enemy Within',
 'Grand Theft Auto: Liberty City Stories',
 'Lego Star Wars: The Force Awakens',
 'Need for Speed',
 'Terminator: Resistance',
 'Fable II',
 'Final Fantasy XIII',
 'Bayonetta',
 'Xenoblade Chronicles: Definitive Edition',
 'Marvel Ultimate Alliance 3: The Black Order',
 'Dead Space 2',
 'Duke Nukem 3D',
 'Sonic the Hedgehog',
 'Command & Conquer 3: Tiberium Wars',
 'Vampyr',
 'Deus Ex',
 'Stargate SG-1: Unleashed',
 'Fortnite: Chapter 2',
 'God of War: Chains of Olympus',
 'Dark Souls II',
 'GhostWire: Tokyo',
 'Catwoman: The Game',
 'Call of the Dead',
 'Forza Horizon 4',
 'Final Fantasy XII',
 'Back 4 Blood',
 'Lego Batman: The Videogame',
 'Guilty Gear: Strive',
 'Metro 2033',
 'Prototype',
 'Destiny',
 'Return to Castle Wolfenstein',
 "Teenage Mutant Ninja Turtles: Shredder's Revenge",
 'Grand Theft Auto Online',
 'Grand Theft Auto 2',
 'Judgment',
 "Dante's Inferno",
 'Jak and Daxter: The Precursor Legacy',
 'Sonic and the Fallen Star',
 'Wing Commander III: Heart of the Tiger',
 'Reservoir Dogs',
 'Fallout 2: A Post-Nuclear Role-Playing Game',
 'Lego Batman 2: DC Super Heroes',
 'Need for Speed: Heat',
 "Garry's Mod",
 'Gears of War',
 'Halo 3: ODST',
 'New Rally-X',
 'World of Warcraft',
 'Diablo Immortal',
 '007: Nightfire',
 'True Crime: Streets of LA',
 'Roblox',
 'The Lord of the Rings: Gollum',
 'Grand Theft Auto IV: The Lost and Damned',
 'Tekken',
 'Dead Island',
 'Red Dead Redemption: Undead Nightmare',
 "Baldur's Gate III",
 'Heavenly Sword',
 'ARK: Genesis - Part 2',
 "Demon's Souls",
 'Deus Ex: Mankind Divided',
 'Ratchet & Clank',
 'Anthem',
 'Doom 3',
 'Star Wars: Squadrons',
 'Disney Infinity 3.0',
 'Hitman: Blood Money',
 'Mobile Legends: Bang Bang',
 'The Simpsons: Hit & Run',
 'Postal 2',
 'The Order: 1886',
 'Harry Potter and the Goblet of Fire',
 'Marvel Future Revolution',
 'Vampire: The Masquerade - Bloodlines',
 'For Honor',
 'The Mummy: Tomb of the Dragon Emperor',
 'T2: Terminator 2: Judgment Day',
 'Iron Man',
 'Yakuza',
 'Battlefield 3',
 'Splinter Cell',
 'Sniper Elite 5',
 'Kena: Bridge of Spirits',
 'Destroy All Humans!',
 'Resident Evil: Revelations 2',
 'True Crime: New York City',
 'Tomb Raider',
 'Shadow of the Colossus',
 'Star Wars: Battlefront II',
 'The Elder Scrolls Online: Morrowind',
 'Darksiders',
 'Crash Bandicoot',
 'The X Files: Resist or Serve',
 'Need for Speed: Underground 2',
 'Fable',
 'Star Wars: Episode I - The Phantom Menace',
 'Ben 10 Ultimate Alien: Cosmic Destruction',
 'The DioField Chronicle',
 'Street Fighter V',
 'Resident Evil 3: Nemesis',
 'Black Ops 4: Dead of the Night',
 'Call of Duty: Advanced Warfare - Exo Zombies',
 'Jak II',
 'Total War: Warhammer II',
 'Deus Ex: Human Revolution',
 'Battlefield: Hardline',
 'Rocket League',
 'Harry Potter and the Half-Blood Prince',
 'Super Smash Bros. Brawl',
 'Resident Evil: Code: Veronica',
 'Tekken 4',
 'Sonic Adventure',
 'Persona 4 Golden',
 'Castlevania: Lords of Shadow 2',
 'The Dark Knight Rises',
 'Sonic the Hedgehog 2',
 'Harry Potter and the Chamber of Secrets',
 'Need for Speed: Undercover',
 'Dead Rising',
 'Predator 2',
 'Need for Speed: Carbon',
 'Harry Potter and the Order of the Phoenix',
 'Super Mario Odyssey',
 'Castlevania: Lords of Shadow',
 'Aliens: Colonial Marines',
 'The Getaway',
 'Shin Megami Tensei: Persona 4',
 'Darksiders II',
 'Destroy All Humans! 2',
 'Call of Duty 2',
 'Enter the Matrix',
 'BMX XXX',
 'Star Wars: Episode III - Revenge of the Sith',
 'Immortals Fenyx Rising',
 'Star Wars: Battlefront',
 'Hunt Down the Freeman',
 'Call of Duty: Modern Warfare Remastered',
 'Need for Speed: Most Wanted',
 'Spyro Reignited Trilogy',
 'Alice',
 'Psychonauts',
 'Nickelodeon All-Star Brawl',
 'Gears of War 3',
 'Kingdom Hearts: Birth by Sleep',
 'Gears of War 4',
 'Prince of Persia',
 'Devil May Cry',
 'Sonic Frontiers',
 'Far Cry 3: Blood Dragon',
 'Outriders',
 'Wolfenstein',
 "Assassin's Creed: The Ezio Collection",
 'Halo: The Master Chief Collection',
 'Overwatch 2',
 'Attack on Titan',
 'Wonder Woman',
 'Sonic Heroes',
 'Dead Space 3',
 'Wolfenstein: Youngblood',
 'Resident Evil HD Remaster',
 'Thor: God of Thunder',
 'Metal Gear Solid V: Ground Zeroes',
 'The Legend of Zelda: Twilight Princess',
 'Guardians of the Galaxy: The Telltale Series',
 "Devil May Cry 3: Dante's Awakening",
 'Indigo Prophecy',
 "The Legend of Zelda: Majora's Mask",
 'House Party',
 'Horizon Zero Dawn: The Frozen Wilds',
 'Super Mario Galaxy',
 'The Wolf Among Us 2',
 'Smite',
 'Alien vs. Predator',
 'The Elder Scrolls III: Morrowind',
 'Marvel: Ultimate Alliance',
 'Lego Jurassic World',
 'Devil May Cry 4',
 'Crash Bandicoot: The Wrath of Cortex',
 'Crysis',
 'Sifu',
 'The Forest',
 'Avatar: The Last Airbender - The Legend of Aang',
 'High on Life',
 'Adventure at the Center of the Earth',
 'Shadow of the Colossus',
 'The Dinosaur Game',
 'Resident Evil: Revelations',
 'Legacy of Kain: Soul Reaver',
 'Uncharted: Legacy of Thieves Collection',
 'Super Mario Sunshine',
 'Hotline Miami',
 'Bayonetta 2',
 'Monster Hunter: World',
 'John Wick Hex',
 'Tekken 5',
 "Asura's Wrath",
 'Metro: Last Light',
 'Spec Ops: The Line',
 'Aliens vs. Predator 2',
 'Sunset Overdrive',
 'Prince of Persia: The Forgotten Sands',
 'Grand Theft Auto: The Trilogy - The Definitive Edition',
 'Final Fantasy XIV: Heavensward',
 'Final Fantasy XIV: Shadowbringers',
 'Just Cause 2',
 "Harry Potter and the Sorcerer's Stone",
 'Captain America: Super Soldier',
 'XCOM 2: War of the Chosen',
 'Lego Star Wars: The Complete Saga',
 'Starfield',
 'Mortal Kombat',
 'Enslaved: Odyssey to the West',
 "The Nightmare Before Christmas: Oogie's Revenge",
 'Prey',
 'Space Ace',
 'Spider-Man: Friend or Foe',
 'Goat Simulator',
 'Divinity: Original Sin II',
 'Crazy Taxi',
 'Sonic Forces',
 'Tekken 2',
 'Outlast: Whistleblower',
 'inFamous',
 'Neon White',
 'StarCraft II: Wings of Liberty',
 'Just Cause 3',
 'Honkai Impact 3rd',
 'Uncharted: Golden Abyss',
 'The Division 2',
 'Stranglehold',
 'The Simpsons Game',
 'Yakuza Kiwami 2',
 'Need for Speed: Payback',
 'Ratchet & Clank',
 'Turok',
 'Crouching Tiger, Hidden Dragon',
 'Transformers: Fall of Cybertron',
 'A Series of Unfortunate Events',
 'Hitman 2: Silent Assassin',
 'World War Z',
 'Grand Theft Auto Advance',
 'Stranger Things 3: The Game',
 'Jump Force',
 'Prince of Persia: The Two Thrones',
 'Avengers: Damage Control',
 'The Division',
 'GreedFall',
 'Wing Commander IV: The Price of Freedom',
 "Tom Clancy's Rainbow Six Extraction",
 'Super Mario World',
 'Chrono Trigger',
 'The Darkness',
 "Death Stranding Director's Cut",
 'Tomb Raider: Legend',
 'Aliens: Fireteam Elite',
 "Dragon's Dogma",
 'Family Guy: Back to the Multiverse',
 'Skylanders: Trap Team',
 'Fight Club',
 'Ben 10 Protector of Earth',
 'Diablo III: Reaper of Souls',
 'Sonic Unleashed',
 'Super Seducer 2',
 'Guild Wars 2',
 'Fleeing the Complex',
 'Counter-Strike: Global Offensive',
 'The Lord of the Rings: The Return of the King',
 'The Witcher 3: Wild Hunt - Hearts of Stone',
 'Driv3r',
 'Avatar: Frontiers of Pandora',
 'Darksiders Genesis',
 'Watchmen: The End Is Nigh',
 'Charlie and the Chocolate Factory',
 'Rage 2',
 'Star Wars: The Force Unleashed II',
 'Hulk',
 'Rust',
 'Triangle Strategy',
 'Jumanji: The Video Game',
 'Ready or Not',
 'Trover Saves the Universe',
 'Splatoon 3',
 'Warhammer 40,000: Chaos Gate - Daemonhunters',
 'Alone in the Dark',
 'Warhammer 40,000: Space Marine',
 'Spider-Man 2: The Game',
 'The Amazing Spider-Man',
 'Tekken 6',
 'Lego City Undercover',
 'Dead Rising 3',
 'Mortal Kombat vs. DC Universe',
 'TRON 2.0',
 "Mirror's Edge",
 'Splinter Cell: Chaos Theory',
 'Donkey Kong Country',
 'Star Trek Online',
 'Prototype 2',
 'Castlevania: Symphony of the Night',
 'Zombieland VR: Headshot Fever',
 'Wolfenstein: The Old Blood',
 'Star Wars: The Old Republic - Onslaught',
 'Toy Story 3: The Video Game',
 'Rumble Roses XX',
 'The Legend of Zelda: A Link to the Past',
 'SpongeBob SquarePants: Battle for Bikini Bottom',
 'Transformers: War for Cybertron',
 'StarCraft',
 'Stranger of Paradise: Final Fantasy Origin',
 'Boneworks',
 'Spider-Man Unlimited',
 'Wolfenstein 3D',
 'Madagascar',
 'Finding Nemo',
 'Plants vs. Zombies',
 'inFamous 2',
 'Tomb Raider: Anniversary',
 'The Legend of Korra',
 'Gears Tactics',
 'GoldenEye: Rogue Agent',
 "PlayerUnknown's Battlegrounds",
 'State of Survival',
 '007 Legends',
 'Ruined King: A League of Legends Story',
 'Super Smash Bros. Melee',
 'Dead Rising 2',
 "Them's Fightin' Herds",
 "Mirror's Edge: Catalyst",
 'Command & Conquer: Red Alert',
 'Spider-Man 2 (PSP)',
 'Skate 3',
 'Clash of Clans',
 'Crysis 3',
 'Spider-Man',
 'Legends of Runeterra',
 'The Legend of Zelda',
 'Doom 64',
 'Metal Gear Solid: Peace Walker',
 'Batman: Arkham Origins - Blackgate',
 'Sonic & Knuckles',
 'Splinter Cell: Conviction',
 'Bulletstorm',
 'The Hobbit',
 'WWE SmackDown! Here Comes the Pain',
 'Agents of Mayhem',
 'Pokémon Legends: Arceus',
 'South Park',
 'Yakuza 6: The Song of Life',
 'The Goonies',
 'Top Gun',
 'Hatred',
 'Brawl Stars',
 'Hyrule Warriors: Age of Calamity',
 'One Punch Man: A Hero Nobody Knows',
 'Rogue Company',
 'Wasteland 3',
 'Pokémon Red Version',
 'Medal of Honor',
 'Warframe',
 'Scarlet Nexus',
 'Darksiders III',
 'Crash Bandicoot N. Sane Trilogy',
 'Final Fantasy XIV',
 'Star Wars: The Old Republic - Knights of the Fallen Empire',
 'Twisted Metal 2: World Tour',
 'Star Wars: Knights of the Old Republic Remake',
 'Wet',
 'Infamous: First Light',
 'Chorus',
 'The Lego Movie Videogame',
 'World of Warcraft: Legion',
 'Sherlock Holmes: Chapter One',
 'Crysis 2',
 'Shin Megami Tensei: Persona 3',
 'Gears of War 2',
 'Resident Evil Zero',
 'Pathfinder: Wrath of the Righteous',
 'Dino Crisis 2',
 'Angry Birds',
 'F.E.A.R. First Encounter Assault Recon',
 'Terminator 3: Rise of the Machines',
 'Crash Bandicoot: Warped',
 'King Kong: The Official Game of the Movie',
 'Transformers: The Game',
 'Lost in Random',
 'Hitman: Codename 47',
 'Predator: Concrete Jungle',
 'Dead Space',
 'Sonic Mania',
 'Soulcalibur VI',
 'Star Trek',
 'Little Nicky',
 'Soul Hackers 2',
 'Mortal Kombat II',
 'The Henry Stickmin Collection',
 'Jurassic Park: The Game',
 'Killer Instinct',
 'Seaquest DSV',
 'Final Fantasy XIII-2',
 'Persona 5 Strikers',
 'The Elder Scrolls II: Daggerfall',
 'Dungeons & Dragons: Dark Alliance',
 'Buffy the Vampire Slayer',
 'Nioh',
 'Tron: Evolution',
 'Star Wars: Republic Commando',
 'Ben 10 Omniverse',
 'XIII',
 'The Outlast Trials',
 'Full Throttle',
 'Buffy the Vampire Slayer: Chaos Bleeds',
 'Kingdom Hearts IV',
 'Alien vs. Predator',
 'Boyfriend Dungeon',
 'Borderlands: The Pre-Sequel!',
 'Call of Duty: Mobile',
 'Let It Die',
 'Harry Potter and the Prisoner of Azkaban',
 'State of Decay 2',
 'Final Fantasy XIV: Stormblood',
 'Ace Combat 7: Skies Unknown',
 'Kingdoms of Amalur: Reckoning',
 'Kick-Ass: The Game',
 'Pillars of Eternity',
 'Black Mesa',
 'The Shield',
 'The Incredibles',
 'The Chronicles of Narnia',
 'Blitz: The League 2',
 "Assassin's Creed III: Liberation",
 'Fight Night Champion',
 'Rage',
 'XIII',
 'Dragon Ball FighterZ',
 'Bloodborne: The Old Hunters',
 'Final Fantasy VIII',
 'Mario Kart Wii',
 'Clash Royale',
 'Star Wars: Jedi Knight - Jedi Academy',
 'A Hat in Time',
 'Quake',
 'Tomb Raider: Underworld',
 'The Saboteur',
 'Harry Potter and the Deathly Hallows: Part I',
 'Grand Theft Auto: Episodes from Liberty City',
 'Batman: Arkham City - Catwoman',
 'Homefront: The Revolution',
 'South Park: Phone Destroyer',
 'Blasphemous',
 'Condemned: Criminal Origins',
 'Dishonored: Death of the Outsider',
 'Final Fantasy XIV: A Realm Reborn',
 'Homefront',
 "Baldur's Gate",
 'Destroy All Humans! 2: Reprobed',
 'Samurai Jack: Battle Through Time',
 'Iron Man 2',
 'Despicable Me: Minion Rush',
 'BCV: Battle Construction Vehicles',
 'Postal 4: No Regerts',
 'Aliens vs. Predator',
 'Super Mario Galaxy 2',
 'Nioh 2',
 'Lego Star Wars: The Video Game',
 'Raft',
 'Tomorrow Never Dies',
 'Call of Duty 3',
 'XCOM 2',
 'Kinect Rush: A Disney-Pixar Adventure',
 'Sonic Generations',
 'Teenage Mutant Ninja Turtles IV: Turtles in Time',
 'PlayStation All-Stars Battle Royale',
 'Live a Live',
 'Bloodpath: New Dawn',
 'Thief',
 'Spider-Man 2: Enter Electro',
 'Dragonball Legends',
 'Star Wars: Jedi Knight II - Jedi Outcast',
 'The Texas Chainsaw Massacre',
 "Sword of the Berserk: Guts' Rage",
 "Demon's Souls",
 'Sonic Omens',
 'BioShock Infinite: Burial at Sea',
 'Medal of Honor: Above and Beyond',
 'The Lord of the Rings: The Battle for Middle-earth II - The Rise of the Witch-king',
 'Sniper Elite 4',
 'Ben 10 Omniverse 2',
 'Terraria',
 'Power Rangers: Battle for the Grid',
 'Agony',
 'Alan Wake Remastered',
 'The Legend of Spyro: Dawn of the Dragon',
 'Jak 3',
 'Avatar: The Game',
 'Half-Life 2: Episode Two',
 'Final Fantasy VI',
 'TMNT',
 'Fantastic Four',
 'New Super Mario Bros. Wii',
 'Giraffe Town',
 'Monster Hunter: Rise',
 'Subway Surfers',
 'God Hand',
 'Dota Underlords',
 'Marvel: Ultimate Alliance 2',
 'The Last Airbender',
 'Final Fantasy X-2',
 'Dead Rising 4',
 'Bee Movie Game',
 'Lego the Hobbit: The Video Game',
 'The Suffering',
 'Conan Exiles',
 'Perfect Dark',
 'Rayman Legends',
 'Warcraft III: Reign of Chaos',
 'Elex II',
 'Command & Conquer: Tiberian Sun',
 'The Getaway: Black Monday',
 'Legacy of Kain: Defiance',
 'Zombieland: Double Tap - Road Trip',
 "Pirates of the Caribbean: At World's End",
 'Fire Emblem Heroes',
 "Command & Conquer: Yuri's Revenge",
 'Ratchet: Deadlocked',
 'Back to the Future: The Game',
 'Sly Cooper and the Thievius Raccoonus',
 "Skylanders: Spyro's Adventure",
 'Final Fantasy XVI',
 'Mortal Kombat: Shaolin Monks',
 'Syphon Filter',
 'Transformers: Revenge of the Fallen',
 'Bayonetta 3',
 'Superman',
 'Batman: Arkham VR',
 'Need for Speed: Underground',
 'Kingdom Hearts 3D: Dream Drop Distance',
 'Ice Age 2: The Meltdown',
 'The Divergent Series: Insurgent - Shatter Reality',
 'Puyo Puyo: The Movie',
 'Untitled the Legend of Zelda: Breath of the Wild Sequel',
 'Rise to Honor',
 'Warhammer: Vermintide 2',
 'Beowulf: The Game',
 'Lightning Returns: Final Fantasy XIII',
 'My Summer Car',
 'Naruto Shippûden: Ultimate Ninja Storm 4',
 'Lego Pirates of the Caribbean: The Video Game',
 'Code Vein',
 'Tomb Raider II',
 "Castlevania III: Dracula's Curse",
 'Green Lantern: Rise of the Manhunters',
 'The Thing',
 'Dino Crisis',
 'Pathfinder: Kingmaker',
 "Baldur's Gate II: Shadows of Amn",
 'Night at the Museum: Battle of the Smithsonian',
 'Sly 2: Band of Thieves',
 'Shin Megami Tensei V',
 'Plants vs. Zombies 3',
 'Splatoon 2',
 'I.G.I.-2: Covert Strike',
 'Kirby and the Forgotten Land',
 'Medal of Honor: Warfighter',
 "Baldi's Basics in Education and Learning",
 'The SpongeBob Squarepants Movie',
 'Ratchet & Clank: Up Your Arsenal',
 'Star Wars: Jedi Knight - Dark Forces II',
 'Street Fighter II: The World Warrior',
 'Toy Story',
 'WWE SmackDown! vs. RAW',
 'The Lord of the Rings: The Battle for Middle-Earth',
 'Ghost Rider',
 'Mario Kart: Double Dash!!',
 'Punch-Out!!',
 'Driver: San Francisco',
 "Assassin's Creed: Freedom Cry",
 'Battlefield: Bad Company 2',
 'Metal Gear',
 'Dragon Ball Z: Budokai Tenkaichi 3',
 'Disney Infinity: Marvel Super Heroes',
 'Need for Speed: The Run',
 'Bloodshore',
 'War Thunder',
 'Lego Harry Potter: Years 1-4',
 'Batman: Vengeance',
 'Doom II: Hell on Earth',
 'Call of Duty: Modern Warfare 2 Campaign Remastered',
 'Eragon',
 'Resistance: Fall of Man',
 '007: Agent Under Fire',
 'The Walking Dead: Survival Instinct',
 'Hitman: Contracts',
 'Spyro the Dragon',
 'Area 51',
 'Lego the Lord of the Rings: The Video Game',
 'Black',
 'Blood',
 'The Goonies II',
 'Star Wars: Battlefront',
 'Duke Nukem Forever',
 'Space Jam',
 'Crash Bandicoot 2: Cortex Strikes Back',
 'Star Wars: Eclipse',
 ]  # Add more as needed

# Create a folder to store images
os.makedirs("game_images", exist_ok=True)

for game in game_list:
    folder_name = os.path.join("game_images", game.replace(" ", "_").replace(":", "").replace("'", ""))
    os.makedirs(folder_name, exist_ok=True)
    
    google_crawler = GoogleImageCrawler(storage={"root_dir": folder_name})
    google_crawler.crawl(keyword=game + " game", max_num=1)  # You can increase max_num if needed

print(f"Downloading image for: {game}")
google_crawler.crawl(keyword=game + " game", max_num=1)
print(f"Downloaded for: {game}")
